'use strict';
const S=window.Study,$=id=>document.getElementById(id),admin=document.body.dataset.feedback==='admin';
const statusNames={new:'未対応',checking:'確認中',done:'対応済み'},categories={bug:'不具合',idea:'改善案',other:'その他'};
let page=1,hasNext=false,busy=false,generation=0,detailId=null,ready=false;
function note(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
function clear(){generation++;ready=false;detailId=null;$('list').replaceChildren();$('detail').replaceChildren();if($('send-form')){$('send-form').reset();$('send-form').hidden=true;$('previews').replaceChildren();}note('ログインしてから利用してください。');}
async function run(work){if(busy)return;busy=true;const ticket=generation;const controls=[...document.querySelectorAll('button,input,textarea,select')],states=controls.map(x=>x.disabled);controls.forEach(x=>x.disabled=true);try{await work(ticket);}catch(e){if(ticket===generation){note(e.message,true);if(e.status===401 || e.status===403)clear();}}finally{busy=false;controls.forEach((x,i)=>{if(x.isConnected)x.disabled=states[i];});$('prev').disabled=!ready || page===1;$('next').disabled=!ready || !hasNext;}}
function para(parent,text){const p=document.createElement('p');p.textContent=text;parent.append(p);return p;}
async function show(id,ticket=generation){const item=await S.api('feedback_detail',{id});if(ticket!==generation)return;detailId=id;$('detail').replaceChildren();const h=document.createElement('h2');h.textContent='フィードバックの内容';$('detail').append(h);para($('detail'),categories[item.category]+' ／ '+statusNames[item.status]+' ／ '+new Date(item.created_at).toLocaleString('ja-JP'));if(admin)para($('detail'),'送信者ID：'+item.sender);const body=para($('detail'),item.body);body.className='feedback-body';for(const [i,img] of item.images.entries()){if(!img.url){para($('detail'),'画像を取得できませんでした。もう一度開いてください。');continue;}const image=document.createElement('img');image.src=img.url;image.alt='添付画像 '+(i+1);image.className='feedback-image';image.referrerPolicy='no-referrer';$('detail').append(image);}if(item.images.length)para($('detail'),'画像が読み込めないときは、一覧からもう一度開いてください。');if(admin){const label=document.createElement('label');label.textContent='対応状況';const select=document.createElement('select');for(const [v,text] of Object.entries(statusNames)){const o=document.createElement('option');o.value=v;o.textContent=text;select.append(o);}select.value=item.status;label.append(select);const save=document.createElement('button');save.type='button';save.textContent='対応状況を保存';save.onclick=()=>run(async t=>{await S.api('feedback_status',{id,status:select.value,revision:item.revision});if(t!==generation)return;await load(t);await show(id,t);note('対応状況を保存しました。管理者の操作履歴にも残ります。');});$('detail').append(label,save);} $('detail').hidden=false;}
async function load(ticket=generation){const data=await S.api('feedback_list',{page,admin});if(ticket!==generation)return;hasNext=data.hasNext;$('list').replaceChildren();$('page').textContent=page+'ページ';for(const item of data.items){const row=document.createElement('article');row.className='user-row';para(row,categories[item.category]+' ／ '+statusNames[item.status]+' ／ '+new Date(item.created_at).toLocaleString('ja-JP'));para(row,item.preview);para(row,'添付画像：'+item.image_count+'枚');const button=document.createElement('button');button.type='button';button.className='secondary';button.textContent='内容を見る';button.onclick=()=>run(t=>show(item.id,t));row.append(button);$('list').append(row);}if(!data.items.length)para($('list'),'フィードバックはまだありません。');if(admin){const stats=await S.api('feedback_stats');if(ticket===generation)$('unresolved').textContent='未対応・確認中：'+stats.unresolved+'件';}}
function validateFiles(files){if(files.length>3)throw new Error('画像は１回３枚までです。');for(const file of files){if(!['image/png','image/jpeg','image/webp'].includes(file.type) || file.size>2097152 || file.size<12)throw new Error('PNG・JPEG・WebPの画像を、１枚２MB以内で選んでください。');}}
async function cleanImage(file){const image=await createImageBitmap(file);try{if(image.width*image.height>24000000 || image.width<1 || image.height<1)throw new Error('画像が大きすぎます。小さくして選び直してください。');const scale=Math.min(1,1920/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',0.85));if(!blob || blob.size>2097152)throw new Error('画像を小さくして選び直してください。');return new File([blob],'image.webp',{type:'image/webp'});}finally{image.close();}}
if(!S || S.setupError){note(S?.setupError || '通信設定を確認してください。',true);}else{
 S.client.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT')clear();});
 $('prev').onclick=()=>run(async t=>{if(page>1){page--;await load(t);}});$('next').onclick=()=>run(async t=>{if(hasNext){page++;await load(t);}});$('refresh').onclick=()=>run(async t=>{await load(t);if(detailId)await show(detailId,t);});
 if(!admin){$('images').onchange=()=>{try{validateFiles([...$('images').files]);$('previews').textContent=[...$('images').files].map(f=>f.name).join(' ／ ');note('添付する画像を選びました。');}catch(e){$('images').value='';$('previews').replaceChildren();note(e.message,true);}};
 $('send-form').onsubmit=e=>{e.preventDefault();run(async ticket=>{const files=[...$('images').files];validateFiles(files);const body=$('body').value.trim();if(body.length<10 || body.length>2000)throw new Error('内容を10〜2000文字で具体的に書いてください。');const form=new FormData();form.set('category',$('category').value);form.set('body',body);note('送信しています…');for(const file of files)form.append('images',await cleanImage(file));if(ticket!==generation)return;const result=await S.sendFeedback(form);if(ticket!==generation)return;$('send-form').reset();$('previews').replaceChildren();page=1;await load(ticket);await show(result.id,ticket);note('フィードバックを送信しました。ありがとう！');});};}
 run(async ticket=>{const {data,error}=await S.client.auth.getSession();if(error || !data.session)throw new Error('アカウント画面でログインしてから開いてください。');if(admin)await S.api('feedback_stats');await load(ticket);if(ticket!==generation)return;ready=true;if($('send-form'))$('send-form').hidden=false;note(admin?'フィードバックを確認できます。':'不具合や改善案を送ってください。');});
}
