'use strict';
(async()=>{
 const S=window.Study,$=id=>document.getElementById(id);let actor=null,epoch=0,busy=false,deck=null,question=null,draftId=crypto.randomUUID(),questionId=crypto.randomUUID(),deckDirty=false,questionDirty=false;
 const note=(text,error=false)=>{$('message').textContent=text;$('message').classList.toggle('error',error);};
 const mayLeave=scope=>!(scope==='question'?questionDirty:deckDirty||questionDirty)||confirm('未保存の入力があります。入力を破棄して切り替えますか？');
 const ids=['title','description','genre','subject','grade'];
 function showQuestion(q){question=q;$('delete-question').hidden=!q;questionId=q?.id||crypto.randomUUID();questionDirty=false;$('question-form').hidden=false;$('question-heading').textContent=q?'問題を編集':'新しい問題';for(const f of ['prompt','answer','explanation','hint'])$('q-'+f).value=q?.[f]||'';$('q-position').value=q?q.position+1:Math.min(150,Math.max(-1,...deck.questions.map(x=>x.position))+2);}
 function publication(){const status=deck?.publication_status||'unpublished';$('publish-panel').hidden=!deck;$('publication-status').textContent=({published:'公開中',unpublished:'非公開',blocked:'管理者による公開停止中'}[status]||status)+(deck?.moderation_reason?'：'+deck.moderation_reason:'');$('publish-deck').textContent=status==='published'?'公開内容を更新する':'保存済みの内容を公開する';$('publish-deck').hidden=status==='blocked';$('unpublish-deck').hidden=status!=='published';$('public-link').hidden=status!=='published';$('public-link').href=deck?'decks.html?community='+encodeURIComponent(deck.id):'decks.html';}
 function renderQuestions(){publication();const qs=deck?.questions||[];$('question-count').textContent=deck?qs.length+' / 150問を保存済み':'まずデッキ設定を保存してください。';$('question-list').replaceChildren();for(const q of qs){const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=(q.position+1)+'. '+q.prompt.slice(0,70);b.onclick=()=>{if(!busy&&mayLeave('question')){showQuestion(q);$('q-prompt').focus();}};$('question-list').append(b);} $('study-link').hidden=!qs.length;$('study-link').href=deck?'decks.html?personal='+encodeURIComponent(deck.id):'decks.html';}
 function showDeck(d){deck=d;$('delete-deck').hidden=!d;$('delete-question').hidden=true;draftId=d?.id||crypto.randomUUID();deckDirty=false;questionDirty=false;question=null;for(const f of ids)$('d-'+f).value=d?.[f]||(f==='genre'?'自分の学習':'');$('deck-status').textContent=d?'保存済み':'新しいデッキ・未保存';$('reopen').hidden=!d;$('question-form').hidden=true;$('new-question').disabled=!d;renderQuestions();}
 function clear(){showDeck(null);$('q-prompt').value='';$('q-answer').value='';$('q-explanation').value='';$('q-hint').value='';$('q-position').value=1;$('deck-list').replaceChildren();$('deck-count').textContent='';$('workspace').hidden=true;$('guest').hidden=false;}
 async function api(action,input,ticket){const result=await S.api(action,input);if(ticket!==epoch)throw new Error('アカウントが切り替わりました。');return result;}
 async function list(ticket){const rows=await api('personal_decks',{},ticket);$('deck-list').replaceChildren();$('deck-count').textContent=rows.length+' / 10デッキ';for(const d of rows){const entry=document.createElement('div');entry.className='personal-entry';const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent=d.title;b.onclick=()=>run(async t=>{if(mayLeave())showDeck(await api('personal_deck',{id:d.id},t));});const p=document.createElement('p');p.className='muted';p.textContent=({published:'公開中',unpublished:'非公開',blocked:'公開停止中'}[d.publication_status]||'非公開')+'・'+d.question_count+'問・'+d.subject+' / '+d.grade;entry.append(b,p);$('deck-list').append(entry);}if(!rows.length){const p=document.createElement('p');p.textContent='まだありません。「デッキを作る」から始めよう。';$('deck-list').append(p);}}
 async function run(work){if(busy||!actor)return;const t=epoch;busy=true;const controls=[...$('workspace').querySelectorAll('button,input,textarea')],states=controls.map(x=>x.disabled);controls.forEach(x=>x.disabled=true);$('workspace').setAttribute('aria-busy','true');try{await work(t);}catch(e){if(t===epoch){note(e.message,true);if(e.status===401||e.status===403){actor=null;epoch++;clear();busy=false;$('workspace').removeAttribute('aria-busy');}}}finally{if(t===epoch){busy=false;$('workspace').removeAttribute('aria-busy');controls.forEach((x,i)=>x.disabled=states[i]);$('new-question').disabled=!deck;}}}
 $('deck-form').onsubmit=e=>{e.preventDefault();run(async t=>{const input={id:draftId,revision:deck?.revision||0};for(const f of ids)input[f]=$('d-'+f).value;$('reopen').hidden=false;const saved=await api('personal_save_deck',input,t);deck=saved;$('delete-deck').hidden=false;deckDirty=false;$('deck-status').textContent='保存済み';$('reopen').hidden=false;renderQuestions();await list(t);note('デッキを保存しました。次は問題を追加しよう。');});};
 $('question-form').onsubmit=e=>{e.preventDefault();const next=e.submitter?.value!=='stay';run(async t=>{const input={id:questionId,deck_id:deck.id,revision:question?.revision||0,position:Number($('q-position').value)-1};for(const f of ['prompt','answer','explanation','hint'])input[f]=$('q-'+f).value;deck=await api('personal_save_question',input,t);questionDirty=false;renderQuestions();showQuestion(next?null:deck.questions.find(x=>x.id===input.id));await list(t);note('問題を保存しました。'+(next?'続けて次の問題を入力できます。':'同じ問題を編集できます。'));$('q-prompt').focus();});};
 $('publish-deck').onclick=()=>run(async t=>{if(deckDirty||questionDirty)throw new Error('先に編集中のデッキ設定・問題を保存してください。');if(!confirm('保存済みの問題・答え・解説・ヒントを誰でも読める状態にします。個人情報や公開してはいけない内容がないことを確認しましたか？'))return;deck=await api('community_publish',{id:deck.id,revision:deck.revision,publication_revision:deck.publication_revision||0,confirm:'公開する',question_versions:deck.questions.map(q=>({id:q.id,revision:q.revision}))},t);publication();await list(t);note('保存済みの内容を公開しました。');});
 $('unpublish-deck').onclick=()=>run(async t=>{if(!confirm('このデッキの公開を停止しますか？'))return;const result=await api('community_unpublish',{id:deck.id,publication_revision:deck.publication_revision||0},t);deck={...deck,publication_status:result.publication_status,publication_revision:result.publication_revision,moderation_reason:result.moderation_reason};publication();await list(t);note('公開を停止しました。個人用デッキと編集中の入力は残っています。');});
 function clearLocalNotes(id,questions){try{for(const q of questions)for(const suffix of ['text','ink'])localStorage.removeItem('study-personal:'+actor+':'+id+':'+q.id+':'+suffix);}catch{}}
 $('delete-deck').onclick=()=>run(async t=>{if(!deck)return;if(!confirm('「'+deck.title+'」と全問題を削除します。公開も停止し、元に戻せません。未保存の入力も失われます。削除しますか？'))return;const target=deck;await api('personal_delete_deck',{id:target.id,revision:target.revision,publication_revision:target.publication_revision||0,question_versions:target.questions.map(q=>({id:q.id,revision:q.revision})),confirm:'削除する'},t);clearLocalNotes(target.id,target.questions);showDeck(null);note('個人デッキを削除しました。公開も停止しました。');await list(t);});
 $('delete-question').onclick=()=>run(async t=>{if(!question||!deck)return;if(deckDirty)throw new Error('先にデッキ設定を保存してください。');if(!confirm('この問題と編集中の入力を削除しますか？元に戻せません。公開済みの内容は、公開を更新・停止するまで残ります。'))return;const target=question;deck=await api('personal_delete_question',{id:target.id,deck_id:deck.id,revision:target.revision,confirm:'削除する'},t);clearLocalNotes(deck.id,[target]);questionDirty=false;$('question-form').hidden=true;question=null;$('delete-question').hidden=true;renderQuestions();await list(t);note('個人用の問題を削除しました。公開済みの内容は更新・停止するまで残ります。');});
 $('new-deck').onclick=()=>{if(!busy&&mayLeave())showDeck(null);};$('new-question').onclick=()=>{if(!busy&&mayLeave('question')){showQuestion(null);$('q-prompt').focus();}};
 $('refresh').onclick=()=>run(async t=>{await list(t);note('一覧を更新しました。編集中の入力はそのままです。');});
 $('reopen').onclick=()=>run(async t=>{if(mayLeave())showDeck(await api('personal_deck',{id:draftId},t));});
 $('study-link').onclick=e=>{if(busy||!mayLeave())e.preventDefault();};
 $('deck-form').addEventListener('input',()=>deckDirty=true);$('question-form').addEventListener('input',()=>questionDirty=true);
 window.addEventListener('beforeunload',e=>{if(actor&&(deckDirty||questionDirty)){e.preventDefault();e.returnValue='';}});
 $('question-form').addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!busy){e.preventDefault();$('question-form').requestSubmit($('save-next'));}});
 if(!S||S.setupError){note(S?.setupError||'接続設定を確認してください。',true);return;}
 function sessionChanged(session){const next=session?.user?.id||null;if(next===actor)return;epoch++;actor=next;busy=false;$('workspace').removeAttribute('aria-busy');clear();for(const x of $('workspace').querySelectorAll('button,input,textarea'))x.disabled=false;$('new-question').disabled=true;if(actor){$('guest').hidden=true;$('workspace').hidden=false;setTimeout(()=>run(async t=>{await list(t);const requested=new URLSearchParams(location.search).get('deck');if(requested)showDeck(await api('personal_deck',{id:requested},t));note('自分だけのデッキを作って学習できます。');}),0);}else note('アカウント画面からログインしてください。');}
 S.client.auth.onAuthStateChange((event,session)=>sessionChanged(session));
 const initialEpoch=epoch;const {data,error}=await S.client.auth.getSession();if(epoch===initialEpoch){if(error)note('ログインし直してください。',true);else sessionChanged(data.session);}if(!actor){$('guest').hidden=false;if(!error)note('アカウント画面からログインしてください。');}
})();
